import './globals.css'

import { Karla } from 'next/font/google'
import type { Metadata } from 'next'

import Cursor from './components/Cursor'


const karla = Karla({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <Cursor />
        {children}
      </body>
    </html>
  )
}
